[package]
name = "gantry-crane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
argh = "0.1.9"
bollard = "0.13.0"
env_logger = "0.9.1"
figment = { version = "0.10.7", features = ["env", "toml"] }
futures = "0.3.25"
log = "0.4.17"
paho-mqtt = "0.11.1"
serde = { version = "1.0.145", features = ["rc"] }
serde_json = "1.0.85"
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = "0.1.10"
