poll_interval = 60

[mqtt]
host = "localhost"
port = 1883
username = ""
password = ""
# client_id = "gantry-crane-1"

[homeassistant]
active = true
base_topic = "homeassistant"
node_id = "gantry-crane"
