poll_interval = 60
filter_by_label = false

[mqtt]
host = "localhost"
port = 1883
username = ""
password = ""
client_id = "gantry-crane"
base_topic = "gantry-crane"

[homeassistant]
active = true
base_topic = "homeassistant"
node_id = "gantry-crane"
