name: Docker

on:
  push:
    branches:
      - master
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  docker_publish:
    name: Build & publish docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
              philw07/gantry-crane
              ghcr.io/philw07/gantry-crane
          tags: |
              type=edge,branch=master
              type=semver,pattern={{version}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push images 
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: >-
            linux/amd64,
            linux/arm/v7,
            linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-to: type=gha,mode=max
          cache-from: type=gha
